<?php

namespace Database\Seeders;

use Illuminate\Database\Console\Seeds\WithoutModelEvents;
use Illuminate\Database\Seeder;
use App\Models\Country;

class CountrySeeder extends Seeder
{
    /**
     * Run the database seeds.
     */
    public function run(): void
    {
        //
        $countries = [
            [
                'name' => 'Afghanistan',
                'iso2' => '93',
                'iso3' => 'AF',
                'currency' => '',
                'symbol' => '',
            ],
            [
                'name' => 'Albania',
                'iso2' => '355',
                'iso3' => 'AL',
                'currency' => '',
                'symbol' => '',
            ],
            [
                'name' => 'Algeria',
                'iso2' => '213',
                'iso3' => 'DZ',
                'currency' => '',
                'symbol' => '',
            ],
            [
                'name' => 'American Samoa',
                'iso2' => '1-684',
                'iso3' => 'AS',
                'currency' => '',
                'symbol' => '',
            ],
            [
                'name' => 'Andorra',
                'iso2' => '376',
                'iso3' => 'AD',
                'currency' => '',
                'symbol' => '',
            ],
            [
                'name' => 'Angola',
                'iso2' => '244',
                'iso3' => 'AO',
                'currency' => '',
                'symbol' => '',
            ],
            [
                'name' => 'Anguilla',
                'iso2' => '1-264',
                'iso3' => 'AI',
                'currency' => '',
                'symbol' => '',
            ],
            [
                'name' => 'Antarctica',
                'iso2' => '672',
                'iso3' => 'AQ',
                'currency' => '',
                'symbol' => '',
            ],
            [
                'name' => 'Antigua and Barbuda',
                'iso2' => '1-268',
                'iso3' => 'AG',
                'currency' => '',
                'symbol' => '',
            ],
            [
                'name' => 'Argentina',
                'iso2' => '54',
                'iso3' => 'AR',
                'currency' => '',
                'symbol' => '',
            ],
            [
                'name' => 'Armenia',
                'iso2' => '374',
                'iso3' => 'AM',
                'currency' => '',
                'symbol' => '',
            ],
            [
                'name' => 'Aruba',
                'iso2' => '297',
                'iso3' => 'AW',
                'currency' => '',
                'symbol' => '',
            ],
            [
                'name' => 'Australia',
                'iso2' => '61',
                'iso3' => 'AU',
                'currency' => '',
                'symbol' => '',
            ],
            [
                'name' => 'Austria',
                'iso2' => '43',
                'iso3' => 'AT',
                'currency' => '',
                'symbol' => '',
            ],
            [
                'name' => 'Azerbaijan',
                'iso2' => '994',
                'iso3' => 'AZ',
                'currency' => '',
                'symbol' => '',
            ],
            [
                'name' => 'Bahamas',
                'iso2' => '1-242',
                'iso3' => 'BS',
                'currency' => '',
                'symbol' => '',
            ],
            [
                'name' => 'Bahrain',
                'iso2' => '973',
                'iso3' => 'BH',
                'currency' => '',
                'symbol' => '',
            ],
            [
                'name' => 'Bangladesh',
                'iso2' => '880',
                'iso3' => 'BD',
                'currency' => '',
                'symbol' => '',
            ],
            [
                'name' => 'Barbados',
                'iso2' => '1-246',
                'iso3' => 'BB',
                'currency' => '',
                'symbol' => '',
            ],
            [
                'name' => 'Belarus',
                'iso2' => '375',
                'iso3' => 'BY',
                'currency' => '',
                'symbol' => '',
            ],
            [
                'name' => 'Belgium',
                'iso2' => '32',
                'iso3' => 'BE',
                'currency' => '',
                'symbol' => '',
            ],
            [
                'name' => 'Belize',
                'iso2' => '501',
                'iso3' => 'BZ',
                'currency' => '',
                'symbol' => '',
            ],
            [
                'name' => 'Benin',
                'iso2' => '229',
                'iso3' => 'BJ',
                'currency' => '',
                'symbol' => '',
            ],
            [
                'name' => 'Bermuda',
                'iso2' => '1-441',
                'iso3' => 'BM',
                'currency' => '',
                'symbol' => '',
            ],
            [
                'name' => 'Bhutan',
                'iso2' => '975',
                'iso3' => 'BT',
                'currency' => '',
                'symbol' => '',
            ],
            [
                'name' => 'Bolivia',
                'iso2' => '591',
                'iso3' => 'BO',
                'currency' => '',
                'symbol' => '',
            ],
            [
                'name' => 'Bosnia and Herzegovina',
                'iso2' => '387',
                'iso3' => 'BA',
                'currency' => '',
                'symbol' => '',
            ],
            [
                'name' => 'Botswana',
                'iso2' => '267',
                'iso3' => 'BW',
                'currency' => '',
                'symbol' => '',
            ],
            [
                'name' => 'Brazil',
                'iso2' => '55',
                'iso3' => 'BR',
                'currency' => '',
                'symbol' => '',
            ],
            [
                'name' => 'British Indian Ocean Territory',
                'iso2' => '246',
                'iso3' => 'IO',
                'currency' => '',
                'symbol' => '',
            ],
            [
                'name' => 'British Virgin Islands',
                'iso2' => '1-284',
                'iso3' => 'VG',
                'currency' => '',
                'symbol' => '',
            ],
            [
                'name' => 'Brunei',
                'iso2' => '673',
                'iso3' => 'BN',
                'currency' => '',
                'symbol' => '',
            ],
            [
                'name' => 'Bulgaria',
                'iso2' => '359',
                'iso3' => 'BG',
                'currency' => '',
                'symbol' => '',
            ],
            [
                'name' => 'Burkina Faso',
                'iso2' => '226',
                'iso3' => 'BF',
                'currency' => '',
                'symbol' => '',
            ],
            [
                'name' => 'Burundi',
                'iso2' => '257',
                'iso3' => 'BI',
                'currency' => '',
                'symbol' => '',
            ],
            [
                'name' => 'Cambodia',
                'iso2' => '855',
                'iso3' => 'KH',
                'currency' => '',
                'symbol' => '',
            ],
            [
                'name' => 'Cameroon',
                'iso2' => '237',
                'iso3' => 'CM',
                'currency' => '',
                'symbol' => '',
            ],
            [
                'name' => 'Canada',
                'iso2' => '1',
                'iso3' => 'CA',
                'currency' => '',
                'symbol' => '',
            ],
            [
                'name' => 'Cape Verde',
                'iso2' => '238',
                'iso3' => 'CV',
                'currency' => '',
                'symbol' => '',
            ],
            [
                'name' => 'Cayman Islands',
                'iso2' => '1-345',
                'iso3' => 'KY',
                'currency' => '',
                'symbol' => '',
            ],
            [
                'name' => 'Central African Republic',
                'iso2' => '236',
                'iso3' => 'CF',
                'currency' => '',
                'symbol' => '',
            ],
            [
                'name' => 'Chad',
                'iso2' => '235',
                'iso3' => 'TD',
                'currency' => '',
                'symbol' => '',
            ],
            [
                'name' => 'Chile',
                'iso2' => '56',
                'iso3' => 'CL',
                'currency' => '',
                'symbol' => '',
            ],
            [
                'name' => 'China',
                'iso2' => '86',
                'iso3' => 'CN',
                'currency' => '',
                'symbol' => '',
            ],
            [
                'name' => 'Christmas Island',
                'iso2' => '61',
                'iso3' => 'CX', 'currency' => '',
                'symbol' => '',
            ],
            [
                'name' => 'Cocos Islands',
                'iso2' => '61',
                'iso3' => 'CC',
                'currency' => '',
                'symbol' => '',
            ],
            [
                'name' => 'Colombia',
                'iso2' => '57',
                'iso3' => 'CO',
                'currency' => '',
                'symbol' => '',
            ],
            [
                'name' => 'Comoros',
                'iso2' => '269',
                'iso3' => 'KM',
                'currency' => '',
                'symbol' => '',
            ],
            [
                'name' => 'Cook Islands',
                'iso2' => '682',
                'iso3' => 'CK',
                'currency' => '',
                'symbol' => '',
            ],
            [
                'name' => 'Costa Rica',
                'iso2' => '506',
                'iso3' => 'CR',
                'currency' => '',
                'symbol' => '',
            ],
            [
                'name' => 'Croatia',
                'iso2' => '385',
                'iso3' => 'HR',
                'currency' => '',
                'symbol' => '',
            ],
            [
                'name' => 'Cuba',
                'iso2' => '53',
                'iso3' => 'CU',
                'currency' => '',
                'symbol' => '',
            ],
            [
                'name' => 'Curacao',
                'iso2' => '599',
                'iso3' => 'CW',
                'currency' => '',
                'symbol' => '',
            ],
            [
                'name' => 'Cyprus',
                'iso2' => '357',
                'iso3' => 'CY',
                'currency' => '',
                'symbol' => '',
            ],
            [
                'name' => 'Czech Republic',
                'iso2' => '420',
                'iso3' => 'CZ',
                'currency' => '',
                'symbol' => '',
            ],
            [
                'name' => 'Democratic Republic of the Congo',
                'iso2' => '243',
                'iso3' => 'CD',
                'currency' => '',
                'symbol' => '',
            ],
            [
                'name' => 'Denmark',
                'iso2' => '45',
                'iso3' => 'DK',
                'currency' => '',
                'symbol' => '',
            ],
            [
                'name' => 'Djibouti',
                'iso2' => '253',
                'iso3' => 'DJ',
                'currency' => '',
                'symbol' => '',
            ],
            [
                'name' => 'Dominica',
                'iso2' => '1-767',
                'iso3' => 'DM',
                'currency' => '',
                'symbol' => '',
            ],
            [
                'name' => 'Dominican Republic',
                'iso2' => '1-809, 1-829, 1-849',
                'iso3' => 'DO',
                'currency' => '',
                'symbol' => '',
            ],
            [
                'name' => 'East Timor',
                'iso2' => '670',
                'iso3' => 'TL',
                'currency' => '',
                'symbol' => '',
            ],
            [
                'name' => 'Ecuador',
                'iso2' => '593',
                'iso3' => 'EC',
                'currency' => '',
                'symbol' => '',
            ],
            [
                'name' => 'Egypt',
                'iso2' => '20',
                'iso3' => 'EG',
                'currency' => '',
                'symbol' => '',
            ],
            [
                'name' => 'El Salvador',
                'iso2' => '503',
                'iso3' => 'SV',
                'currency' => '',
                'symbol' => '',
            ],
            [
                'name' => 'Equatorial Guinea',
                'iso2' => '240',
                'iso3' => 'GQ',
                'currency' => '',
                'symbol' => '',
            ],
            [
                'name' => 'Eritrea',
                'iso2' => '291',
                'iso3' => 'ER',
                'currency' => '',
                'symbol' => '',
            ],
            [
                'name' => 'Estonia',
                'iso2' => '372',
                'iso3' => 'EE',
                'currency' => '',
                'symbol' => '',
            ],
            [
                'name' => 'Ethiopia',
                'iso2' => '251',
                'iso3' => 'ET',
                'currency' => '',
                'symbol' => '',
            ],
            [
                'name' => 'Falkland Islands',
                'iso2' => '500',
                'iso3' => 'FK',
                'currency' => '',
                'symbol' => '',
            ],
            [
                'name' => 'Faroe Islands',
                'iso2' => '298',
                'iso3' => 'FO',
                'currency' => '',
                'symbol' => '',
            ],
            [
                'name' => 'Fiji',
                'iso2' => '679',
                'iso3' => 'FJ',
                'currency' => '',
                'symbol' => '',
            ],
            [
                'name' => 'Finland',
                'iso2' => '358',
                'iso3' => 'FI',
                'currency' => '',
                'symbol' => '',
            ],
            [
                'name' => 'France',
                'iso2' => '33',
                'iso3' => 'FR',
                'currency' => '',
                'symbol' => '',
            ],
            [
                'name' => 'French Polynesia',
                'iso2' => '689',
                'iso3' => 'PF',
                'currency' => '',
                'symbol' => '',
            ],
            [
                'name' => 'Gabon',
                'iso2' => '241',
                'iso3' => 'GA',
                'currency' => '',
                'symbol' => '',
            ],
            [
                'name' => 'Gambia',
                'iso2' => '220',
                'iso3' => 'GM',
                'currency' => '',
                'symbol' => '',
            ],
            [
                'name' => 'Georgia',
                'iso2' => '995',
                'iso3' => 'GE',
                'currency' => '',
                'symbol' => '',
            ],
            [
                'name' => 'Germany',
                'iso2' => '49',
                'iso3' => 'DE',
                'currency' => '',
                'symbol' => '',
            ],
            [
                'name' => 'Ghana',
                'iso2' => '233',
                'iso3' => 'GH',
                'currency' => '',
                'symbol' => '',
            ],
            [
                'name' => 'Gibraltar',
                'iso2' => '350',
                'iso3' => 'GI',
                'currency' => '',
                'symbol' => '',
            ],
            [
                'name' => 'Greece',
                'iso2' => '30',
                'iso3' => 'GR',
                'currency' => '',
                'symbol' => '',
            ],
            [
                'name' => 'Greenland',
                'iso2' => '299',
                'iso3' => 'GL',
                'currency' => '',
                'symbol' => '',
            ],
            [
                'name' => 'Grenada',
                'iso2' => '1-473',
                'iso3' => 'GD',
                'currency' => '',
                'symbol' => '',
            ],
            [
                'name' => 'Guam',
                'iso2' => '1-671',
                'iso3' => 'GU',
                'currency' => '',
                'symbol' => '',
            ],
            [
                'name' => 'Guatemala',
                'iso2' => '502',
                'iso3' => 'GT',
                'currency' => '',
                'symbol' => '',
            ],
            [
                'name' => 'Guernsey',
                'iso2' => '44-1481',
                'iso3' => 'GG',
                'currency' => '',
                'symbol' => '',
            ],
            [
                'name' => 'Guinea',
                'iso2' => '224',
                'iso3' => 'GN',
                'currency' => '',
                'symbol' => '',
            ],
            [
                'name' => 'Guinea-Bissau',
                'iso2' => '245',
                'iso3' => 'GW',
                'currency' => '',
                'symbol' => '',
            ],
            [
                'name' => 'Guyana',
                'iso2' => '592',
                'iso3' => 'GY',
                'currency' => '',
                'symbol' => '',
            ],
            [
                'name' => 'Haiti',
                'iso2' => '509',
                'iso3' => 'HT',
                'currency' => '',
                'symbol' => '',
            ],
            [
                'name' => 'Honduras',
                'iso2' => '504',
                'iso3' => 'HN',
                'currency' => '',
                'symbol' => '',
            ],
            [
                'name' => 'Hong Kong',
                'iso2' => '852',
                'iso3' => 'HK',
                'currency' => '',
                'symbol' => '',
            ],
            [
                'name' => 'Hungary',
                'iso2' => '36',
                'iso3' => 'HU',
                'currency' => '',
                'symbol' => '',
            ],
            [
                'name' => 'Iceland',
                'iso2' => '354',
                'iso3' => 'IS',
                'currency' => '',
                'symbol' => '',
            ],
            [
                'name' => 'India',
                'iso2' => '91',
                'iso3' => 'IN',
                'currency' => '',
                'symbol' => '',
            ],
            [
                'name' => 'Indonesia',
                'iso2' => '62',
                'iso3' => 'ID',
                'currency' => '',
                'symbol' => '',
            ],
            [
                'name' => 'Iran',
                'iso2' => '98',
                'iso3' => 'IR',
                'currency' => '',
                'symbol' => '',
            ],
            [
                'name' => 'Iraq',
                'iso2' => '964',
                'iso3' => 'IQ',
                'currency' => '',
                'symbol' => '',
            ],
            [
                'name' => 'Ireland',
                'iso2' => '353',
                'iso3' => 'IE',
                'currency' => '',
                'symbol' => '',
            ],
            [
                'name' => 'Isle of Man',
                'iso2' => '44-1624',
                'iso3' => 'IM',
                'currency' => '',
                'symbol' => '',
            ],
            [
                'name' => 'Israel',
                'iso2' => '972',
                'iso3' => 'IL',
                'currency' => '',
                'symbol' => '',
            ],
            [
                'name' => 'Italy',
                'iso2' => '39',
                'iso3' => 'IT',
                'currency' => '',
                'symbol' => '',
            ],
            [
                'name' => 'Ivory Coast',
                'iso2' => '225',
                'iso3' => 'CI',
                'currency' => '',
                'symbol' => '',
            ],
            [
                'name' => 'Jamaica',
                'iso2' => '1-876',
                'iso3' => 'JM',
                'currency' => '',
                'symbol' => '',
            ],
            [
                'name' => 'Japan',
                'iso2' => '81',
                'iso3' => 'JP',
                'currency' => '',
                'symbol' => '',
            ],
            [
                'name' => 'Jersey',
                'iso2' => '44-1534',
                'iso3' => 'JE',
                'currency' => '',
                'symbol' => '',
            ],
            [
                'name' => 'Jordan',
                'iso2' => '962',
                'iso3' => 'JO',
                'currency' => '',
                'symbol' => '',
            ],
            [
                'name' => 'Kazakhstan',
                'iso2' => '7',
                'iso3' => 'KZ',
                'currency' => '',
                'symbol' => '',
            ],
            [
                'name' => 'Kenya',
                'iso2' => '254',
                'iso3' => 'KE',
                'currency' => '',
                'symbol' => '',
            ],
            [
                'name' => 'Kiribati',
                'iso2' => '686',
                'iso3' => 'KI',
                'currency' => '',
                'symbol' => '',
            ],
            [
                'name' => 'Kosovo',
                'iso2' => '383',
                'iso3' => 'XK',
                'currency' => '',
                'symbol' => '',
            ],
            [
                'name' => 'Kuwait',
                'iso2' => '965',
                'iso3' => 'KW',
                'currency' => '',
                'symbol' => '',
            ],
            [
                'name' => 'Kyrgyzstan',
                'iso2' => '996',
                'iso3' => 'KG',
                'currency' => '',
                'symbol' => '',
            ],
            [
                'name' => 'Laos',
                'iso2' => '856',
                'iso3' => 'LA',
                'currency' => '',
                'symbol' => '',
            ],
            [
                'name' => 'Latvia',
                'iso2' => '371',
                'iso3' => 'LV',
                'currency' => '',
                'symbol' => '',
            ],
            [
                'name' => 'Lebanon',
                'iso2' => '961',
                'iso3' => 'LB',
                'currency' => '',
                'symbol' => '',
            ],
            [
                'name' => 'Lesotho',
                'iso2' => '266',
                'iso3' => 'LS',
                'currency' => '',
                'symbol' => '',
            ],
            [
                'name' => 'Liberia',
                'iso2' => '231',
                'iso3' => 'LR',
                'currency' => '',
                'symbol' => '',
            ],
            [
                'name' => 'Libya',
                'iso2' => '218',
                'iso3' => 'LY',
                'currency' => '',
                'symbol' => '',
            ],
            [
                'name' => 'Liechtenstein',
                'iso2' => '423',
                'iso3' => 'LI',
                'currency' => '',
                'symbol' => '',
            ],
            [
                'name' => 'Lithuania',
                'iso2' => '370',
                'iso3' => 'LT',
                'currency' => '',
                'symbol' => '',
            ],
            [
                'name' => 'Luxembourg',
                'iso2' => '352',
                'iso3' => 'LU',
                'currency' => '',
                'symbol' => '',
            ],
            [
                'name' => 'Macau',
                'iso2' => '853',
                'iso3' => 'MO',
                'currency' => '',
                'symbol' => '',
            ],
            [
                'name' => 'Macedonia',
                'iso2' => '389',
                'iso3' => 'MK',
                'currency' => '',
                'symbol' => '',
            ],
            [
                'name' => 'Madagascar',
                'iso2' => '261',
                'iso3' => 'MG',
                'currency' => '',
                'symbol' => '',
            ],
            [
                'name' => 'Malawi',
                'iso2' => '265',
                'iso3' => 'MW',
                'currency' => '',
                'symbol' => '',
            ],
            [
                'name' => 'Malaysia',
                'iso2' => '60',
                'iso3' => 'MY',
                'currency' => '',
                'symbol' => '',
            ],
            [
                'name' => 'Maldives',
                'iso2' => '960',
                'iso3' => 'MV',
                'currency' => '',
                'symbol' => '',
            ],
            [
                'name' => 'Mali',
                'iso2' => '223',
                'iso3' => 'ML',
                'currency' => '',
                'symbol' => '',
            ],
            [
                'name' => 'Malta',
                'iso2' => '356',
                'iso3' => 'MT',
                'currency' => '',
                'symbol' => '',
            ],
            [
                'name' => 'Marshall Islands',
                'iso2' => '692',
                'iso3' => 'MH',
                'currency' => '',
                'symbol' => '',
            ],
            [
                'name' => 'Mauritania',
                'iso2' => '222',
                'iso3' => 'MR',
                'currency' => '',
                'symbol' => '',
            ],
            [
                'name' => 'Mauritius',
                'iso2' => '230',
                'iso3' => 'MU',
                'currency' => '',
                'symbol' => '',
            ],
            [
                'name' => 'Mayotte',
                'iso2' => '262',
                'iso3' => 'YT',
                'currency' => '',
                'symbol' => '',
            ],
            [
                'name' => 'Mexico',
                'iso2' => '52',
                'iso3' => 'MX',
                'currency' => '',
                'symbol' => '',
            ],
            [
                'name' => 'Micronesia',
                'iso2' => '691',
                'iso3' => 'FM',
                'currency' => '',
                'symbol' => '',
            ],
            [
                'name' => 'Moldova',
                'iso2' => '373',
                'iso3' => 'MD',
                'currency' => '',
                'symbol' => '',
            ],
            [
                'name' => 'Monaco',
                'iso2' => '377',
                'iso3' => 'MC',
                'currency' => '',
                'symbol' => '',
            ],
            [
                'name' => 'Mongolia',
                'iso2' => '976',
                'iso3' => 'MN',
                'currency' => '',
                'symbol' => '',
            ],
            [
                'name' => 'Montenegro',
                'iso2' => '382',
                'iso3' => 'ME',
                'currency' => '',
                'symbol' => '',
            ],
            [
                'name' => 'Montserrat',
                'iso2' => '1-664',
                'iso3' => 'MS',
                'currency' => '',
                'symbol' => '',
            ],
            [
                'name' => 'Morocco',
                'iso2' => '212',
                'iso3' => 'MA',
                'currency' => '',
                'symbol' => '',
            ],
            [
                'name' => 'Mozambique',
                'iso2' => '258',
                'iso3' => 'MZ',
                'currency' => '',
                'symbol' => '',
            ],
            [
                'name' => 'Myanmar',
                'iso2' => '95',
                'iso3' => 'MM',
                'currency' => '',
                'symbol' => '',
            ],
            [
                'name' => 'Namibia',
                'iso2' => '264',
                'iso3' => 'NA',
                'currency' => '',
                'symbol' => '',
            ],
            [
                'name' => 'Nauru',
                'iso2' => '674',
                'iso3' => 'NR',
                'currency' => '',
                'symbol' => '',
            ],
            [
                'name' => 'Nepal',
                'iso2' => '977',
                'iso3' => 'NP',
                'currency' => '',
                'symbol' => '',
            ],
            [
                'name' => 'Netherlands',
                'iso2' => '31',
                'iso3' => 'NL',
                'currency' => '',
                'symbol' => '',
            ],
            [
                'name' => 'Netherlands Antilles',
                'iso2' => '599',
                'iso3' => 'AN',
                'currency' => '',
                'symbol' => '',
            ],
            [
                'name' => 'New Caledonia',
                'iso2' => '687',
                'iso3' => 'NC',
                'currency' => '',
                'symbol' => '',
            ],
            [
                'name' => 'New Zealand',
                'iso2' => '64',
                'iso3' => 'NZ',
                'currency' => '',
                'symbol' => '',
            ],
            [
                'name' => 'Nicaragua',
                'iso2' => '505',
                'iso3' => 'NI',
                'currency' => '',
                'symbol' => '',
            ],
            [
                'name' => 'Niger',
                'iso2' => '227',
                'iso3' => 'NE',
                'currency' => '',
                'symbol' => '',
            ],
            [
                'name' => 'Nigeria',
                'iso2' => '234',
                'iso3' => 'NG',
                'currency' => '',
                'symbol' => '',
            ],
            [
                'name' => 'Niue',
                'iso2' => '683',
                'iso3' => 'NU',
                'currency' => '',
                'symbol' => '',
            ],
            [
                'name' => 'North Korea',
                'iso2' => '850',
                'iso3' => 'KP',
                'currency' => '',
                'symbol' => '',
            ],
            [
                'name' => 'Northern Mariana Islands',
                'iso2' => '1-670',
                'iso3' => 'MP',
                'currency' => '',
                'symbol' => '',
            ],
            [
                'name' => 'Norway',
                'iso2' => '47',
                'iso3' => 'NO',
                'currency' => '',
                'symbol' => '',
            ],
            [
                'name' => 'Oman',
                'iso2' => '968',
                'iso3' => 'OM',
                'currency' => '',
                'symbol' => '',
            ],
            [
                'name' => 'Pakistan',
                'iso2' => '92',
                'iso3' => 'PK',
                'currency' => '',
                'symbol' => '',
            ],
            [
                'name' => 'Palau',
                'iso2' => '680',
                'iso3' => 'PW',
                'currency' => '',
                'symbol' => '',
            ],
            [
                'name' => 'Palestine',
                'iso2' => '970',
                'iso3' => 'PS',
                'currency' => '',
                'symbol' => '',
            ],
            [
                'name' => 'Panama',
                'iso2' => '507',
                'iso3' => 'PA',
                'currency' => '',
                'symbol' => '',
            ],
            [
                'name' => 'Papua New Guinea',
                'iso2' => '675',
                'iso3' => 'PG',
                'currency' => '',
                'symbol' => '',
            ],
            [
                'name' => 'Paraguay',
                'iso2' => '595',
                'iso3' => 'PY',
                'currency' => '',
                'symbol' => '',
            ],
            [
                'name' => 'Peru',
                'iso2' => '51',
                'iso3' => 'PE',
                'currency' => '',
                'symbol' => '',
            ],
            [
                'name' => 'Philippines',
                'iso2' => '63',
                'iso3' => 'PH',
                'currency' => '',
                'symbol' => '',
                'is_supported' => true,
            ],
            [
                'name' => 'Pitcairn',
                'iso2' => '64',
                'iso3' => 'PN',
                'currency' => '',
                'symbol' => '',
            ],
            [
                'name' => 'Poland',
                'iso2' => '48',
                'iso3' => 'PL',
                'currency' => '',
                'symbol' => '',
            ],
            [
                'name' => 'Portugal',
                'iso2' => '351',
                'iso3' => 'PT',
                'currency' => '',
                'symbol' => '',
            ],
            [
                'name' => 'Puerto Rico',
                'iso2' => '1-787, 1-939',
                'iso3' => 'PR',
                'currency' => '',
                'symbol' => '',
            ],
            [
                'name' => 'Qatar',
                'iso2' => '974',
                'iso3' => 'QA',
                'currency' => '',
                'symbol' => '',
            ],
            [
                'name' => 'Republic of the Congo',
                'iso2' => '242',
                'iso3' => 'CG',
                'currency' => '',
                'symbol' => '',
            ],
            [
                'name' => 'Reunion',
                'iso2' => '262',
                'iso3' => 'RE',
                'currency' => '',
                'symbol' => '',
            ],
            [
                'name' => 'Romania',
                'iso2' => '40',
                'iso3' => 'RO',
                'currency' => '',
                'symbol' => '',
            ],
            [
                'name' => 'Russia',
                'iso2' => '7',
                'iso3' => 'RU',
                'currency' => '',
                'symbol' => '',
            ],
            [
                'name' => 'Rwanda',
                'iso2' => '250',
                'iso3' => 'RW',
                'currency' => '',
                'symbol' => '',
            ],
            [
                'name' => 'Saint Barthelemy',
                'iso2' => '590',
                'iso3' => 'BL',
                'currency' => '',
                'symbol' => '',
            ],
            [
                'name' => 'Saint Helena',
                'iso2' => '290',
                'iso3' => 'SH',
                'currency' => '',
                'symbol' => '',
            ],
            [
                'name' => 'Saint Kitts and Nevis',
                'iso2' => '1-869',
                'iso3' => 'KN',
                'currency' => '',
                'symbol' => '',
            ],
            [
                'name' => 'Saint Lucia',
                'iso2' => '1-758',
                'iso3' => 'LC',
                'currency' => '',
                'symbol' => '',
            ],
            [
                'name' => 'Saint Martin',
                'iso2' => '590',
                'iso3' => 'MF',
                'currency' => '',
                'symbol' => '',
            ],
            [
                'name' => 'Saint Pierre and Miquelon',
                'iso2' => '508',
                'iso3' => 'PM',
                'currency' => '',
                'symbol' => '',
            ],
            [
                'name' => 'Saint Vincent and the Grenadines',
                'iso2' => '1-784',
                'iso3' => 'VC',
                'currency' => '',
                'symbol' => '',
            ],
            [
                'name' => 'Samoa',
                'iso2' => '685',
                'iso3' => 'WS',
                'currency' => '',
                'symbol' => '',
            ],
            [
                'name' => 'San Marino',
                'iso2' => '378',
                'iso3' => 'SM',
                'currency' => '',
                'symbol' => '',
            ],
            [
                'name' => 'Sao Tome and Principe',
                'iso2' => '239',
                'iso3' => 'ST',
                'currency' => '',
                'symbol' => '',
            ],
            [
                'name' => 'Saudi Arabia',
                'iso2' => '966',
                'iso3' => 'SA',
                'currency' => '',
                'symbol' => '',
            ],
            [
                'name' => 'Senegal',
                'iso2' => '221',
                'iso3' => 'SN',
                'currency' => '',
                'symbol' => '',
            ],
            [
                'name' => 'Serbia',
                'iso2' => '381',
                'iso3' => 'RS',
                'currency' => '',
                'symbol' => '',
            ],
            [
                'name' => 'Seychelles',
                'iso2' => '248',
                'iso3' => 'SC',
                'currency' => '',
                'symbol' => '',
            ],
            [
                'name' => 'Sierra Leone',
                'iso2' => '232',
                'iso3' => 'SL',
                'currency' => '',
                'symbol' => '',
            ],
            [
                'name' => 'Singapore',
                'iso2' => '65',
                'iso3' => 'SG',
                'currency' => '',
                'symbol' => '',
            ],
            [
                'name' => 'Sint Maarten',
                'iso2' => '1-721',
                'iso3' => 'SX',
                'currency' => '',
                'symbol' => '',
            ],
            [
                'name' => 'Slovakia',
                'iso2' => '421',
                'iso3' => 'SK',
                'currency' => '',
                'symbol' => '',
            ],
            [
                'name' => 'Slovenia',
                'iso2' => '386',
                'iso3' => 'SI',
                'currency' => '',
                'symbol' => '',
            ],
            [
                'name' => 'Solomon Islands',
                'iso2' => '677',
                'iso3' => 'SB',
                'currency' => '',
                'symbol' => '',
            ],
            [
                'name' => 'Somalia',
                'iso2' => '252',
                'iso3' => 'SO',
                'currency' => '',
                'symbol' => '',
            ],
            [
                'name' => 'South Africa',
                'iso2' => '27',
                'iso3' => 'ZA',
                'currency' => '',
                'symbol' => '',
            ],
            [
                'name' => 'South Korea',
                'iso2' => '82',
                'iso3' => 'KR',
                'currency' => '',
                'symbol' => '',
            ],
            [
                'name' => 'South Sudan',
                'iso2' => '211',
                'iso3' => 'SS',
                'currency' => '',
                'symbol' => '',
            ],
            [
                'name' => 'Spain',
                'iso2' => '34',
                'iso3' => 'ES',
                'currency' => '',
                'symbol' => '',
            ],
            [
                'name' => 'Sri Lanka',
                'iso2' => '94',
                'iso3' => 'LK',
                'currency' => '',
                'symbol' => '',
            ],
            [
                'name' => 'Sudan',
                'iso2' => '249',
                'iso3' => 'SD',
                'currency' => '',
                'symbol' => '',
            ],
            [
                'name' => 'Suriname',
                'iso2' => '597',
                'iso3' => 'SR',
                'currency' => '',
                'symbol' => '',
            ],
            [
                'name' => 'Svalbard and Jan Mayen',
                'iso2' => '47',
                'iso3' => 'SJ',
                'currency' => '',
                'symbol' => '',
            ],
            [
                'name' => 'Swaziland',
                'iso2' => '268',
                'iso3' => 'SZ',
                'currency' => '',
                'symbol' => '',
            ],
            [
                'name' => 'Sweden',
                'iso2' => '46',
                'iso3' => 'SE',
                'currency' => '',
                'symbol' => '',
            ],
            [
                'name' => 'Switzerland',
                'iso2' => '41',
                'iso3' => 'CH',
                'currency' => '',
                'symbol' => '',
            ],
            [
                'name' => 'Syria',
                'iso2' => '963',
                'iso3' => 'SY',
                'currency' => '',
                'symbol' => '',
            ],
            [
                'name' => 'Taiwan',
                'iso2' => '886',
                'iso3' => 'TW',
                'currency' => '',
                'symbol' => '',
            ],
            [
                'name' => 'Tajikistan',
                'iso2' => '992',
                'iso3' => 'TJ',
                'currency' => '',
                'symbol' => '',
            ],
            [
                'name' => 'Tanzania',
                'iso2' => '255',
                'iso3' => 'TZ',
                'currency' => '',
                'symbol' => '',
            ],
            [
                'name' => 'Thailand',
                'iso2' => '66',
                'iso3' => 'TH',
                'currency' => '',
                'symbol' => '',
            ],
            [
                'name' => 'Togo',
                'iso2' => '228',
                'iso3' => 'TG',
                'currency' => '',
                'symbol' => '',
            ],
            [
                'name' => 'Tokelau',
                'iso2' => '690',
                'iso3' => 'TK',
                'currency' => '',
                'symbol' => '',
            ],
            [
                'name' => 'Tonga',
                'iso2' => '676',
                'iso3' => 'TO',
                'currency' => '',
                'symbol' => '',
            ],
            [
                'name' => 'Trinidad and Tobago',
                'iso2' => '1-868',
                'iso3' => 'TT',
                'currency' => '',
                'symbol' => '',
            ],
            [
                'name' => 'Tunisia',
                'iso2' => '216',
                'iso3' => 'TN',
                'currency' => '',
                'symbol' => '',
            ],
            [
                'name' => 'Turkey',
                'iso2' => '90',
                'iso3' => 'TR',
                'currency' => '',
                'symbol' => '',
            ],
            [
                'name' => 'Turkmenistan',
                'iso2' => '993',
                'iso3' => 'TM',
                'currency' => '',
                'symbol' => '',
            ],
            [
                'name' => 'Turks and Caicos Islands',
                'iso2' => '1-649',
                'iso3' => 'TC',
                'currency' => '',
                'symbol' => '',
            ],
            [
                'name' => 'Tuvalu',
                'iso2' => '688',
                'iso3' => 'TV',
                'currency' => '',
                'symbol' => '',
            ],
            [
                'name' => 'U.S. Virgin Islands',
                'iso2' => '1-340',
                'iso3' => 'VI',
                'currency' => '',
                'symbol' => '',
            ],
            [
                'name' => 'Uganda',
                'iso2' => '256',
                'iso3' => 'UG',
                'currency' => '',
                'symbol' => '',
            ],
            [
                'name' => 'Ukraine',
                'iso2' => '380',
                'iso3' => 'UA',
                'currency' => '',
                'symbol' => '',
            ],
            [
                'name' => 'United Arab Emirates',
                'iso2' => '971',
                'iso3' => 'AE',
                'currency' => '',
                'symbol' => '',
            ],
            [
                'name' => 'United Kingdom',
                'iso2' => '44',
                'iso3' => 'GB',
                'currency' => '',
                'symbol' => '',
            ],
            [
                'name' => 'United States',
                'iso2' => '1',
                'iso3' => 'US',
                'currency' => '',
                'symbol' => '',
            ],
            [
                'name' => 'Uruguay',
                'iso2' => '598',
                'iso3' => 'UY',
                'currency' => '',
                'symbol' => '',
            ],
            [
                'name' => 'Uzbekistan',
                'iso2' => '998',
                'iso3' => 'UZ',
                'currency' => '',
                'symbol' => '',
            ],
            [
                'name' => 'Vanuatu',
                'iso2' => '678',
                'iso3' => 'VU',
                'currency' => '',
                'symbol' => '',
            ],
            [
                'name' => 'Vatican',
                'iso2' => '379',
                'iso3' => 'VA',
                'currency' => '',
                'symbol' => '',
            ],
            [
                'name' => 'Venezuela',
                'iso2' => '58',
                'iso3' => 'VE',
                'currency' => '',
                'symbol' => '',
            ],
            [
                'name' => 'Vietnam',
                'iso2' => '84',
                'iso3' => 'VN',
                'currency' => '',
                'symbol' => '',
            ],
            [
                'name' => 'Wallis and Futuna',
                'iso2' => '681',
                'iso3' => 'WF',
                'currency' => '',
                'symbol' => '',
            ],
            [
                'name' => 'Western Sahara',
                'iso2' => '212',
                'iso3' => 'EH',
                'currency' => '',
                'symbol' => '',
            ],
            [
                'name' => 'Yemen',
                'iso2' => '967',
                'iso3' => 'YE',
                'currency' => '',
                'symbol' => '',
            ],
            [
                'name' => 'Zambia',
                'iso2' => '260',
                'iso3' => 'ZM',
                'currency' => '',
                'symbol' => '',
            ],
            [
                'name' => 'Zimbabwe',
                'iso2' => '263',
                'iso3' => 'ZW',
                'currency' => '',
                'symbol' => '',
            ],
        ];

        foreach ($countries as $key => $country) {
            # code...
            Country::create($country);
        }
    }
}
